/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package praktikum02072026;

/**
 *
 * @author Jaki
 */
public class MenuMakanan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMakanan.class.getName());

    /** Creates new form MenuMakanan */
    public MenuMakanan() {
        initComponents();
        
    }
    private MenuUtama utama;

    public MenuMakanan(MenuUtama utama) {
        this.utama = utama;
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulMakanan = new javax.swing.JLabel();
        chkNasiGoreng = new javax.swing.JCheckBox();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        txtNasgor = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtSoto = new javax.swing.JTextField();
        cbNasgor = new javax.swing.JComboBox<>();
        cbSate = new javax.swing.JComboBox<>();
        cbSoto = new javax.swing.JComboBox<>();
        txtTotalNasgor = new javax.swing.JTextField();
        txtTotalSate = new javax.swing.JTextField();
        txtTotalSoto = new javax.swing.JTextField();
        lblTotalNasgor = new javax.swing.JLabel();
        lblTotalSoto = new javax.swing.JLabel();
        lblTotalSate = new javax.swing.JLabel();
        btnTotal = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudulMakanan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblJudulMakanan.setText("Pilihan Menu Makanan");

        chkNasiGoreng.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkNasiGoreng.setText("Nasi Goreng");
        chkNasiGoreng.addActionListener(this::chkNasiGorengActionPerformed);

        chkSoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkSoto.setText("Soto");
        chkSoto.addActionListener(this::chkSotoActionPerformed);

        chkSate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkSate.setText("Sate");
        chkSate.addActionListener(this::chkSateActionPerformed);

        txtNasgor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtNasgor.setText("0");

        txtSate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSate.setText("0");

        txtSoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtSoto.setText("0");

        cbNasgor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbNasgor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jumlah -", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbNasgor.addActionListener(this::cbNasgorActionPerformed);

        cbSate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbSate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jumlah -", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSate.addActionListener(this::cbSateActionPerformed);

        cbSoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbSoto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jumlah -", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbSoto.addActionListener(this::cbSotoActionPerformed);

        txtTotalNasgor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalNasgor.setText("0");

        txtTotalSate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalSate.setText("0");

        txtTotalSoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalSoto.setText("0");

        lblTotalNasgor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalNasgor.setText("Total");

        lblTotalSoto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalSoto.setText("Total");

        lblTotalSate.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalSate.setText("Total");

        btnTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotal.setText("0");
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblJudulMakanan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNasiGoreng)
                            .addComponent(chkSate)
                            .addComponent(chkSoto))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalNasgor)
                                    .addComponent(lblTotalSoto)
                                    .addComponent(lblTotalSate))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalSate)
                                    .addComponent(txtTotalSoto)
                                    .addComponent(txtTotalNasgor)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(726, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(38, 38, 38)
                .addComponent(btnKembali)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblJudulMakanan)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalNasgor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalSoto)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkNasiGoreng)
                            .addComponent(txtNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbNasgor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSate)
                            .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkSoto)
                            .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnReset))
                .addGap(96, 96, 96))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void chkNasiGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNasiGorengActionPerformed
        txtNasgor.setText("10000");
    }//GEN-LAST:event_chkNasiGorengActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        txtSate.setText("15000");
    }//GEN-LAST:event_chkSateActionPerformed

    private void cbNasgorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNasgorActionPerformed
        int jumlah = (int)cbNasgor.getSelectedIndex();
        double harga=Double.parseDouble(txtNasgor.getText());
        double total=jumlah*harga;
        
        txtTotalNasgor.setText(Double.toString(total));
    }//GEN-LAST:event_cbNasgorActionPerformed

    private void cbSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSateActionPerformed
        int jumlah = (int)cbSate.getSelectedIndex();
        double harga=Double.parseDouble(txtSate.getText());
        double total=jumlah*harga;
        
        txtTotalSate.setText(Double.toString(total));
    }//GEN-LAST:event_cbSateActionPerformed

    private void cbSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSotoActionPerformed
        int jumlah = (int)cbSoto.getSelectedIndex();
        double harga=Double.parseDouble(txtSoto.getText());
        double total=jumlah*harga;
        
        txtTotalSoto.setText(Double.toString(total));
    }//GEN-LAST:event_cbSotoActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double nasgor = Double.parseDouble(txtTotalNasgor.getText());
        double sate = Double.parseDouble(txtTotalSate.getText());
        double soto = Double.parseDouble(txtTotalSoto.getText());
        
        double total = nasgor + sate + soto;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        txtSoto.setText("12000");
    }//GEN-LAST:event_chkSotoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtTotalNasgor.setText("");
        txtTotalSate.setText("");
        txtTotalSoto.setText("");
        txtTotal.setText("");
        cbNasgor.setSelectedIndex(0);
        cbSoto.setSelectedIndex(0);
        cbSate.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMakanan(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMakanan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbNasgor;
    private javax.swing.JComboBox<String> cbSate;
    private javax.swing.JComboBox<String> cbSoto;
    private javax.swing.JCheckBox chkNasiGoreng;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel lblJudulMakanan;
    private javax.swing.JLabel lblTotalNasgor;
    private javax.swing.JLabel lblTotalSate;
    private javax.swing.JLabel lblTotalSoto;
    private javax.swing.JTextField txtNasgor;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalNasgor;
    private javax.swing.JTextField txtTotalSate;
    private javax.swing.JTextField txtTotalSoto;
    // End of variables declaration//GEN-END:variables

}
