/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package praktikum02072026;

/**
 *
 * @author Jaki
 */
public class MenuMinuman extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuMinuman.class.getName());

    /**
     * Creates new form MenuMinuman
     */
    public MenuMinuman() {
        initComponents();
    }
    private MenuUtama utama;
    
    public MenuMinuman(MenuUtama utama) {
        this.utama = utama;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblJudulMakanan = new javax.swing.JLabel();
        txtTotalTehes = new javax.swing.JTextField();
        chkTehes = new javax.swing.JCheckBox();
        txtTotalJusBuah = new javax.swing.JTextField();
        chkKopi = new javax.swing.JCheckBox();
        txtTotalKopi = new javax.swing.JTextField();
        chkJusBuah = new javax.swing.JCheckBox();
        lblTotalTehes = new javax.swing.JLabel();
        lblTotalKopi = new javax.swing.JLabel();
        txtTehes = new javax.swing.JTextField();
        lblTotalJusBuah = new javax.swing.JLabel();
        txtJusBuah = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        txtKopi = new javax.swing.JTextField();
        btnKembali = new javax.swing.JButton();
        cbTehes = new javax.swing.JComboBox<>();
        txtTotal = new javax.swing.JTextField();
        cbJusBuah = new javax.swing.JComboBox<>();
        btnReset = new javax.swing.JButton();
        cbKopi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblJudulMakanan.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblJudulMakanan.setText("Pilihan Menu Minuman");

        txtTotalTehes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalTehes.setText("0");

        chkTehes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkTehes.setText("Teh Es");
        chkTehes.addActionListener(this::chkTehesActionPerformed);

        txtTotalJusBuah.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalJusBuah.setText("0");

        chkKopi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkKopi.setText("Kopi");
        chkKopi.addActionListener(this::chkKopiActionPerformed);

        txtTotalKopi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotalKopi.setText("0");

        chkJusBuah.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkJusBuah.setText("Jus Buah");
        chkJusBuah.addActionListener(this::chkJusBuahActionPerformed);

        lblTotalTehes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalTehes.setText("Total");

        lblTotalKopi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalKopi.setText("Total");

        txtTehes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTehes.setText("0");

        lblTotalJusBuah.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalJusBuah.setText("Total");

        txtJusBuah.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtJusBuah.setText("0");

        btnTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(this::btnTotalActionPerformed);

        txtKopi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtKopi.setText("0");

        btnKembali.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(this::btnKembaliActionPerformed);

        cbTehes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbTehes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jumlah -", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbTehes.addActionListener(this::cbTehesActionPerformed);

        txtTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtTotal.setText("0");
        txtTotal.addActionListener(this::txtTotalActionPerformed);

        cbJusBuah.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbJusBuah.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jumlah -", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbJusBuah.addActionListener(this::cbJusBuahActionPerformed);

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(this::btnResetActionPerformed);

        cbKopi.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbKopi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Jumlah -", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cbKopi.addActionListener(this::cbKopiActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(lblJudulMakanan))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkTehes)
                            .addComponent(chkJusBuah)
                            .addComponent(chkKopi))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtJusBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbJusBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTehes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(cbTehes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotalTehes)
                                    .addComponent(lblTotalKopi)
                                    .addComponent(lblTotalJusBuah))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotalJusBuah)
                                    .addComponent(txtTotalKopi)
                                    .addComponent(txtTotalTehes)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReset)
                .addGap(38, 38, 38)
                .addComponent(btnKembali)
                .addGap(146, 146, 146))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblJudulMakanan)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalTehes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalTehes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotalJusBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalJusBuah))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotalKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalKopi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkTehes)
                            .addComponent(txtTehes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTehes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkJusBuah)
                            .addComponent(txtJusBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJusBuah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkKopi)
                            .addComponent(txtKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbKopi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKembali)
                    .addComponent(btnReset))
                .addGap(96, 96, 96))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkTehesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTehesActionPerformed
        txtTehes.setText("5000");
    }//GEN-LAST:event_chkTehesActionPerformed

    private void chkKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkKopiActionPerformed
        txtKopi.setText("6000");
    }//GEN-LAST:event_chkKopiActionPerformed

    private void chkJusBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkJusBuahActionPerformed
        txtJusBuah.setText("8000");
    }//GEN-LAST:event_chkJusBuahActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double teh = Double.parseDouble(txtTotalTehes.getText());
        double jus = Double.parseDouble(txtTotalJusBuah.getText());
        double kopi = Double.parseDouble(txtTotalKopi.getText());

        double total = teh + jus + kopi;
        txtTotal.setText(Double.toString(total));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        String total = txtTotal.getText();
        utama.setTotalMinuman(total);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void cbTehesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTehesActionPerformed
        int jumlah = (int)cbTehes.getSelectedIndex();
        double harga=Double.parseDouble(txtTehes.getText());
        double total=jumlah*harga;

        txtTotalTehes.setText(Double.toString(total));
    }//GEN-LAST:event_cbTehesActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void cbJusBuahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJusBuahActionPerformed
        int jumlah = (int)cbJusBuah.getSelectedIndex();
        double harga=Double.parseDouble(txtJusBuah.getText());
        double total=jumlah*harga;

        txtTotalJusBuah.setText(Double.toString(total));
    }//GEN-LAST:event_cbJusBuahActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtTotalTehes.setText("");
        txtTotalJusBuah.setText("");
        txtTotalKopi.setText("");
        txtTotal.setText("");
        cbTehes.setSelectedIndex(0);
        cbJusBuah.setSelectedIndex(0);
        cbKopi.setSelectedIndex(0);
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKopiActionPerformed
        int jumlah = (int)cbKopi.getSelectedIndex();
        double harga=Double.parseDouble(txtKopi.getText());
        double total=jumlah*harga;

        txtTotalKopi.setText(Double.toString(total));
    }//GEN-LAST:event_cbKopiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuMinuman().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbJusBuah;
    private javax.swing.JComboBox<String> cbKopi;
    private javax.swing.JComboBox<String> cbTehes;
    private javax.swing.JCheckBox chkJusBuah;
    private javax.swing.JCheckBox chkKopi;
    private javax.swing.JCheckBox chkTehes;
    private javax.swing.JLabel lblJudulMakanan;
    private javax.swing.JLabel lblTotalJusBuah;
    private javax.swing.JLabel lblTotalKopi;
    private javax.swing.JLabel lblTotalTehes;
    private javax.swing.JTextField txtJusBuah;
    private javax.swing.JTextField txtKopi;
    private javax.swing.JTextField txtTehes;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtTotalJusBuah;
    private javax.swing.JTextField txtTotalKopi;
    private javax.swing.JTextField txtTotalTehes;
    // End of variables declaration//GEN-END:variables
}
